// Mock Data for GIKI Food Ordering System
// Realistic scale data as per Milestone 1 requirements

const DATA = {
  // User session (simulated login)
  currentUser: {
    id: "STU001",
    name: "Ali Raza",
    email: "ali.raza@giki.edu.pk",
    userType: "student",
    accountBalance: 2500,
    hostelRoom: "H5-204",
  },

  // Food Outlets
  outlets: [
    {
      id: "cafe",
      name: "Café",
      location: "Student Center",
      status: "open",
      openingTime: "08:00",
      closingTime: "23:00",
      averageWaitTime: 12,
      image: "images/food/cafe.jpg",
    },
    {
      id: "mess",
      name: "Mess",
      location: "Main Dining Hall",
      status: "open",
      openingTime: "07:00",
      closingTime: "22:00",
      averageWaitTime: 8,
      image: "images/food/mess.jpg",
    },
    {
      id: "tuc",
      name: "TUC",
      location: "The University Club",
      status: "open",
      openingTime: "12:00",
      closingTime: "23:30",
      averageWaitTime: 15,
      image: "images/food/tuc.jpg",
    },
    {
      id: "coffee",
      name: "Coffee Shop",
      location: "Library Building",
      status: "closed",
      openingTime: "09:00",
      closingTime: "20:00",
      averageWaitTime: 5,
      image: "images/food/coffee.jpg",
    },
  ],

  // Menu Categories
  categories: [
    "Biryani",
    "Burgers",
    "Drinks",
    "Snacks",
    "Desserts",
    "Rice Dishes",
    "Chinese",
    "BBQ",
    "Sandwiches",
    "Breakfast",
  ],

  // Menu Items (30+ items for realistic scale)
  menuItems: [
    // Café Items
    {
      id: "item001",
      outletId: "cafe",
      name: "Chicken Biryani",
      category: "Biryani",
      price: 350,
      isVegetarian: false,
      spiceLevel: "medium",
      availabilityStatus: "available",
      stock: 5,
      preparationTime: 15,
      description: "Aromatic rice with chicken",
      image: "images/food/chicken-biryani.jpg",
    },
    {
      id: "item002",
      outletId: "cafe",
      name: "Beef Burger",
      category: "Burgers",
      price: 280,
      isVegetarian: false,
      spiceLevel: "mild",
      availabilityStatus: "available",
      stock: 12,
      preparationTime: 10,
      description: "Juicy beef patty with cheese",
      image: "images/food/beef-burger.jpg",
    },
    {
      id: "item003",
      outletId: "cafe",
      name: "Cold Drink",
      category: "Drinks",
      price: 80,
      isVegetarian: true,
      spiceLevel: "none",
      availabilityStatus: "available",
      stock: 50,
      preparationTime: 2,
      description: "Chilled soft drink",
      image: "images/food/cold-drink.jpg",
    },
    {
      id: "item004",
      outletId: "cafe",
      name: "Chicken Wings",
      category: "Snacks",
      price: 320,
      isVegetarian: false,
      spiceLevel: "spicy",
      availabilityStatus: "available",
      stock: 8,
      preparationTime: 12,
      description: "6 pieces crispy wings",
      image: "images/food/wings.jpg",
    },
    {
      id: "item005",
      outletId: "cafe",
      name: "Chocolate Brownie",
      category: "Desserts",
      price: 150,
      isVegetarian: true,
      spiceLevel: "none",
      availabilityStatus: "available",
      stock: 15,
      preparationTime: 3,
      description: "Rich chocolate brownie",
      image: "images/food/brownie.jpg",
    },
    {
      id: "item006",
      outletId: "cafe",
      name: "Club Sandwich",
      category: "Sandwiches",
      price: 250,
      isVegetarian: false,
      spiceLevel: "mild",
      availabilityStatus: "available",
      stock: 10,
      preparationTime: 8,
      description: "Triple decker sandwich",
      image: "images/food/sandwich.jpg",
    },
    {
      id: "item007",
      outletId: "cafe",
      name: "French Fries",
      category: "Snacks",
      price: 120,
      isVegetarian: true,
      spiceLevel: "mild",
      availabilityStatus: "available",
      stock: 25,
      preparationTime: 5,
      description: "Crispy golden fries",
      image: "images/food/fries.jpg",
    },
    {
      id: "item008",
      outletId: "cafe",
      name: "Mutton Biryani",
      category: "Biryani",
      price: 420,
      isVegetarian: false,
      spiceLevel: "spicy",
      availabilityStatus: "low-stock",
      stock: 2,
      preparationTime: 15,
      description: "Premium mutton biryani",
      image: "images/food/mutton-biryani.jpg",
    },

    // Mess Items
    {
      id: "item009",
      outletId: "mess",
      name: "Daal Chawal",
      category: "Rice Dishes",
      price: 100,
      isVegetarian: true,
      spiceLevel: "mild",
      availabilityStatus: "available",
      stock: 100,
      preparationTime: 5,
      description: "Traditional lentils with rice",
      image: "images/food/daal.jpg",
    },
    {
      id: "item010",
      outletId: "mess",
      name: "Chicken Karahi",
      category: "BBQ",
      price: 380,
      isVegetarian: false,
      spiceLevel: "spicy",
      availabilityStatus: "available",
      stock: 20,
      preparationTime: 18,
      description: "Spicy chicken curry",
      image: "images/food/karahi.jpg",
    },
    {
      id: "item011",
      outletId: "mess",
      name: "Vegetable Rice",
      category: "Rice Dishes",
      price: 120,
      isVegetarian: true,
      spiceLevel: "mild",
      availabilityStatus: "available",
      stock: 50,
      preparationTime: 5,
      description: "Mixed vegetable pulao",
      image: "images/food/veg-rice.jpg",
    },
    {
      id: "item012",
      outletId: "mess",
      name: "Chapati (2 pcs)",
      category: "Breakfast",
      price: 40,
      isVegetarian: true,
      spiceLevel: "none",
      availabilityStatus: "available",
      stock: 200,
      preparationTime: 2,
      description: "Fresh wheat bread",
      image: "images/food/chapati.jpg",
    },
    {
      id: "item013",
      outletId: "mess",
      name: "Egg Paratha",
      category: "Breakfast",
      price: 80,
      isVegetarian: false,
      spiceLevel: "mild",
      availabilityStatus: "available",
      stock: 30,
      preparationTime: 8,
      description: "Paratha stuffed with egg",
      image: "images/food/paratha.jpg",
    },
    {
      id: "item014",
      outletId: "mess",
      name: "Mix Sabzi",
      category: "Rice Dishes",
      price: 90,
      isVegetarian: true,
      spiceLevel: "medium",
      availabilityStatus: "available",
      stock: 40,
      preparationTime: 5,
      description: "Seasonal vegetables",
      image: "images/food/sabzi.jpg",
    },
    {
      id: "item015",
      outletId: "mess",
      name: "Chicken Tikka",
      category: "BBQ",
      price: 300,
      isVegetarian: false,
      spiceLevel: "spicy",
      availabilityStatus: "available",
      stock: 15,
      preparationTime: 20,
      description: "Grilled chicken pieces",
      image: "images/food/tikka.jpg",
    },

    // TUC Items
    {
      id: "item016",
      outletId: "tuc",
      name: "Zinger Burger",
      category: "Burgers",
      price: 350,
      isVegetarian: false,
      spiceLevel: "spicy",
      availabilityStatus: "available",
      stock: 18,
      preparationTime: 12,
      description: "Spicy crispy chicken burger",
      image: "images/food/zinger.jpg",
    },
    {
      id: "item017",
      outletId: "tuc",
      name: "Loaded Fries",
      category: "Snacks",
      price: 250,
      isVegetarian: false,
      spiceLevel: "medium",
      availabilityStatus: "available",
      stock: 10,
      preparationTime: 10,
      description: "Fries with cheese & chicken",
      image: "images/food/loaded-fries.jpg",
    },
    {
      id: "item018",
      outletId: "tuc",
      name: "Chicken Chow Mein",
      category: "Chinese",
      price: 300,
      isVegetarian: false,
      spiceLevel: "medium",
      availabilityStatus: "available",
      stock: 12,
      preparationTime: 15,
      description: "Stir-fried noodles",
      image: "images/food/chowmein.jpg",
    },
    {
      id: "item019",
      outletId: "tuc",
      name: "Spring Rolls",
      category: "Chinese",
      price: 200,
      isVegetarian: true,
      spiceLevel: "mild",
      availabilityStatus: "available",
      stock: 20,
      preparationTime: 8,
      description: "Crispy vegetable rolls",
      image: "images/food/rolls.jpg",
    },
    {
      id: "item020",
      outletId: "tuc",
      name: "BBQ Pizza",
      category: "Snacks",
      price: 450,
      isVegetarian: false,
      spiceLevel: "mild",
      availabilityStatus: "available",
      stock: 8,
      preparationTime: 20,
      description: "Medium size BBQ chicken pizza",
      image: "images/food/pizza.jpg",
    },
    {
      id: "item021",
      outletId: "tuc",
      name: "Chicken Fried Rice",
      category: "Chinese",
      price: 280,
      isVegetarian: false,
      spiceLevel: "medium",
      availabilityStatus: "available",
      stock: 15,
      preparationTime: 12,
      description: "Chinese style fried rice",
      image: "images/food/fried-rice.jpg",
    },
    {
      id: "item022",
      outletId: "tuc",
      name: "Mango Shake",
      category: "Drinks",
      price: 180,
      isVegetarian: true,
      spiceLevel: "none",
      availabilityStatus: "available",
      stock: 25,
      preparationTime: 5,
      description: "Fresh mango milkshake",
      image: "images/food/shake.jpg",
    },

    // Coffee Shop Items
    {
      id: "item023",
      outletId: "coffee",
      name: "Cappuccino",
      category: "Drinks",
      price: 150,
      isVegetarian: true,
      spiceLevel: "none",
      availabilityStatus: "unavailable",
      stock: 0,
      preparationTime: 5,
      description: "Classic Italian coffee",
      image: "images/food/cappuccino.jpg",
    },
    {
      id: "item024",
      outletId: "coffee",
      name: "Latte",
      category: "Drinks",
      price: 160,
      isVegetarian: true,
      spiceLevel: "none",
      availabilityStatus: "unavailable",
      stock: 0,
      preparationTime: 5,
      description: "Smooth espresso with milk",
      image: "images/food/latte.jpg",
    },
    {
      id: "item025",
      outletId: "coffee",
      name: "Croissant",
      category: "Breakfast",
      price: 120,
      isVegetarian: true,
      spiceLevel: "none",
      availabilityStatus: "unavailable",
      stock: 0,
      preparationTime: 3,
      description: "Buttery French pastry",
      image: "images/food/croissant.jpg",
    },
    {
      id: "item026",
      outletId: "coffee",
      name: "Blueberry Muffin",
      category: "Desserts",
      price: 140,
      isVegetarian: true,
      spiceLevel: "none",
      availabilityStatus: "unavailable",
      stock: 0,
      preparationTime: 3,
      description: "Fresh baked muffin",
      image: "images/food/muffin.jpg",
    },

    // Additional Items for variety
    {
      id: "item027",
      outletId: "cafe",
      name: "Cheese Burger",
      category: "Burgers",
      price: 260,
      isVegetarian: false,
      spiceLevel: "mild",
      availabilityStatus: "available",
      stock: 14,
      preparationTime: 10,
      description: "Classic cheeseburger",
      image: "images/food/cheeseburger.jpg",
    },
    {
      id: "item028",
      outletId: "mess",
      name: "Aloo Paratha",
      category: "Breakfast",
      price: 70,
      isVegetarian: true,
      spiceLevel: "mild",
      availabilityStatus: "available",
      stock: 35,
      preparationTime: 8,
      description: "Potato stuffed paratha",
      image: "images/food/aloo-paratha.jpg",
    },
    {
      id: "item029",
      outletId: "tuc",
      name: "Chicken Broast",
      category: "BBQ",
      price: 380,
      isVegetarian: false,
      spiceLevel: "medium",
      availabilityStatus: "available",
      stock: 10,
      preparationTime: 18,
      description: "Deep fried chicken",
      image: "images/food/broast.jpg",
    },
    {
      id: "item030",
      outletId: "cafe",
      name: "Ice Cream",
      category: "Desserts",
      price: 100,
      isVegetarian: true,
      spiceLevel: "none",
      availabilityStatus: "available",
      stock: 20,
      preparationTime: 2,
      description: "Vanilla or chocolate",
      image: "images/food/icecream.jpg",
    },
  ],

  // Order History (realistic sample data)
  orderHistory: [
    {
      id: "ORD001",
      userId: "STU001",
      outletId: "cafe",
      orderDateTime: "2025-11-28T13:15:00",
      orderStatus: "delivered",
      totalAmount: 430,
      deliveryType: "pickup",
      items: [
        { itemId: "item001", itemName: "Chicken Biryani", quantity: 1, price: 350, customizations: "Less spicy" },
        { itemId: "item003", itemName: "Cold Drink", quantity: 1, price: 80, customizations: "" },
      ],
      paymentMethod: "account",
      rating: 5,
      feedback: "Great food, quick service!",
    },
    {
      id: "ORD002",
      userId: "STU001",
      outletId: "tuc",
      orderDateTime: "2025-11-27T19:30:00",
      orderStatus: "delivered",
      totalAmount: 350,
      deliveryType: "pickup",
      items: [{ itemId: "item016", itemName: "Zinger Burger", quantity: 1, price: 350, customizations: "Extra sauce" }],
      paymentMethod: "card",
      rating: 4,
      feedback: "Good but slightly delayed",
    },
    {
      id: "ORD003",
      userId: "STU001",
      outletId: "mess",
      orderDateTime: "2025-11-26T12:00:00",
      orderStatus: "delivered",
      totalAmount: 190,
      deliveryType: "pickup",
      items: [
        { itemId: "item009", itemName: "Daal Chawal", quantity: 1, price: 100, customizations: "" },
        { itemId: "item014", itemName: "Mix Sabzi", quantity: 1, price: 90, customizations: "" },
      ],
      paymentMethod: "account",
      rating: 5,
      feedback: "",
    },
    {
      id: "ORD004",
      userId: "STU001",
      outletId: "cafe",
      orderDateTime: "2025-11-25T14:20:00",
      orderStatus: "delivered",
      totalAmount: 400,
      deliveryType: "pickup",
      items: [
        { itemId: "item002", itemName: "Beef Burger", quantity: 1, price: 280, customizations: "No onions" },
        { itemId: "item007", itemName: "French Fries", quantity: 1, price: 120, customizations: "" },
      ],
      paymentMethod: "wallet",
      rating: 4,
      feedback: "Fries were cold",
    },
    {
      id: "ORD005",
      userId: "STU001",
      outletId: "tuc",
      orderDateTime: "2025-11-24T20:15:00",
      orderStatus: "delivered",
      totalAmount: 500,
      deliveryType: "pickup",
      items: [
        { itemId: "item018", itemName: "Chicken Chow Mein", quantity: 1, price: 300, customizations: "" },
        { itemId: "item019", itemName: "Spring Rolls", quantity: 1, price: 200, customizations: "" },
      ],
      paymentMethod: "account",
      rating: 5,
      feedback: "Perfect!",
    },
  ],

  // Active Orders (for staff dashboard)
  activeOrders: [
    {
      id: "ORD101",
      userId: "STU045",
      userName: "Ahmed Khan",
      outletId: "cafe",
      orderDateTime: "2025-11-30T13:05:00",
      orderStatus: "confirmed",
      totalAmount: 430,
      deliveryType: "pickup",
      items: [
        { itemId: "item001", itemName: "Chicken Biryani", quantity: 1, price: 350, customizations: "" },
        { itemId: "item003", itemName: "Cold Drink", quantity: 1, price: 80, customizations: "" },
      ],
      paymentStatus: "paid",
      estimatedCompletionTime: 15,
    },
    {
      id: "ORD102",
      userId: "STU067",
      userName: "Sara Ahmed",
      outletId: "cafe",
      orderDateTime: "2025-11-30T13:08:00",
      orderStatus: "preparing",
      totalAmount: 280,
      deliveryType: "pickup",
      items: [{ itemId: "item002", itemName: "Beef Burger", quantity: 1, price: 280, customizations: "Extra cheese" }],
      paymentStatus: "paid",
      estimatedCompletionTime: 8,
    },
    {
      id: "ORD103",
      userId: "STU089",
      userName: "Bilal Shah",
      outletId: "cafe",
      orderDateTime: "2025-11-30T13:10:00",
      orderStatus: "ready",
      totalAmount: 520,
      deliveryType: "pickup",
      items: [
        { itemId: "item004", itemName: "Chicken Wings", quantity: 1, price: 320, customizations: "Extra spicy" },
        { itemId: "item019", itemName: "Spring Rolls", quantity: 1, price: 200, customizations: "" },
      ],
      paymentStatus: "paid",
      estimatedCompletionTime: 0,
    },
  ],

  // Analytics Data (for admin dashboard)
  analytics: {
    todaySales: 12500,
    todayOrders: 47,
    popularItems: [
      { itemName: "Chicken Biryani", count: 12, revenue: 4200 },
      { itemName: "Zinger Burger", count: 9, revenue: 3150 },
      { itemName: "Beef Burger", count: 8, revenue: 2240 },
      { itemName: "Daal Chawal", count: 15, revenue: 1500 },
      { itemName: "Chicken Wings", count: 6, revenue: 1920 },
    ],
    outletPerformance: [
      { outletName: "Café", orders: 20, revenue: 6800, avgWait: 12 },
      { outletName: "Mess", orders: 18, revenue: 2900, avgWait: 8 },
      { outletName: "TUC", orders: 9, revenue: 2800, avgWait: 15 },
    ],
    lowStockItems: [
      { itemName: "Mutton Biryani", stock: 2, outlet: "Café" },
      { itemName: "Chicken Biryani", stock: 5, outlet: "Café" },
    ],
  },
}

// Helper functions
const DataHelper = {
  getOutletById(id) {
    return DATA.outlets.find((outlet) => outlet.id === id)
  },

  getMenuItemById(id) {
    return DATA.menuItems.find((item) => item.id === id)
  },

  getMenuByOutlet(outletId) {
    return DATA.menuItems.filter((item) => item.outletId === outletId)
  },

  getMenuByCategory(category) {
    return DATA.menuItems.filter((item) => item.category === category)
  },

  searchMenuItems(query) {
    const lowerQuery = query.toLowerCase()
    return DATA.menuItems.filter(
      (item) =>
        item.name.toLowerCase().includes(lowerQuery) ||
        item.category.toLowerCase().includes(lowerQuery) ||
        item.description.toLowerCase().includes(lowerQuery),
    )
  },

  getActiveOrders() {
    return DATA.activeOrders
  },

  updateOrderStatus(orderId, newStatus) {
    const order = DATA.activeOrders.find((o) => o.id === orderId)
    if (order) {
      order.orderStatus = newStatus
      return true
    }
    return false
  },

  updateItemAvailability(itemId, status) {
    const item = DATA.menuItems.find((i) => i.id === itemId)
    if (item) {
      item.availabilityStatus = status
      return true
    }
    return false
  },

  getCurrentUser() {
    return DATA.currentUser
  },
}
